apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq.fullname" . }}-config
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  enabled_plugins: |-
{{ .Values.rabbitmq.plugins | indent 4 }}
  rabbitmq.conf: |-
    ## generated configuration
    {{- if .Values.rabbitmq.diskFreeLimit }}
    disk_free_limit.absolute = {{ .Values.rabbitmq.diskFreeLimit }}
    {{- end }}
    {{- if .Values.rabbitmq.managerPort }}
    management.listener.port = {{ .Values.rabbitmq.managerPort }}
    {{- end }}
{{ .Values.rabbitmq.configuration | indent 4 }}

